# .github/workflows/test.yml
name: Run Tests

on:
  pull_request:
    branches: [main, development] # or whatever branches you want to trigger on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # or whatever version you're using

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Vitest
        working-directory: ./backend
        run: npm test # or your specific test script


    # # Optional: Add test coverage reporting
    # - name: Upload coverage reports
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}  # if you're using Codecov
